fix: add method options to CDKSnapApiFunctions interface
calebfrieze/cdk-snap pull request #19
Opened 2024-08-06 19:36 UTC by wyatt-turn

While working in a project that uses CDKSnap I realized I needed a way to specify that an api function required an api-key but that was missing from CDK-Snap.

Need to add these optional method options to be able to further configure our rest apis.

2024-08-06 20:00 UTC, calebfrieze requested changes

2024-08-06 20:00 UTC, calebfrieze commented on src/restApi.ts
> +	options?: MethodOptions;
lets call this `methodOptions`

2024-08-07 16:10 UTC, wyatt-turn commented on src/restApi.ts
> +	options?: MethodOptions;
Sounds good!

2024-08-07 16:12 UTC, calebfrieze approved these changes

2024-08-07 16:22 UTC, merged

2024-08-07 16:23 UTC, calebfrieze commented
:tada: This PR is included in version 0.6.10 :tada:

The release is available on:
- [GitHub release](https://github.com/calebfrieze/cdk-snap/releases/tag/v0.6.10)
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/cdk-snap/v/0.6.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: